### ISSUE TITLE
Please help us at moddota bug tracker

### ISSUE THREAD

**Issue by darklordabc** [ValveSoftware/openvr#688] opened 2017-12-16 12:46 UTC
Could you please for the love of all things holy, get somebody to help us over at the moddota bug tracker git. We have collated so many bugs but nobody at valve gives two shits. Could you please rattle some cages and get somebody to spend a couple of hours helping us?

You can close this issue now.

**Comment by kisak-valve** [comment] 2017-12-16 16:03
Closing as a duplicate of https://github.com/ValveSoftware/Dota-2/issues/1365.

**Closed by kisak-valve** 2017-12-16 16:03 UTC
