### ISSUE TITLE
Attempting to create input components crashes SteamVR

### ISSUE THREAD

**Issue by walrus** [ValveSoftware/openvr#810] opened 2018-06-06 15:38 UTC
This appears to have been introduced by [last night's update](https://steamcommunity.com/games/250820/announcements/detail/1657768916929647711) to the SteamVR Beta, as my driver code which ran yesterday began to crash SteamVR this morning without my having changed anything.

I've tracked it down to a couple of different lines in my driver, as follows:
```
vr::VRDriverInput()->CreateScalarComponent(propertyContainer, "/input/trigger/value", &triggerHandle, vr::EVRScalarType::VRScalarType_Absolute, vr::EVRScalarUnits::VRScalarUnits_NormalizedOneSided);
vr::VRDriverInput()->CreateBooleanComponent(propertyContainer, "/input/trackpad/touch", &trackpadTouchHandle);
vr::VRDriverInput()->CreateScalarComponent(propertyContainer, "/input/axis3/x", &indexHandle, vr::EVRScalarType::VRScalarType_Absolute, vr::EVRScalarUnits::VRScalarUnits_NormalizedOneSided);
```

Any of these crashes SteamVR when included, despite returning `VRInputError_None` before today (and being the recommended way of doing this). If instead I don't create any input components; everything runs fine but of course doesn't do anything useful.

I'm not sure whether this is connected to the following bit of the latest update (it's difficult to tell as that's the only information we seem to have on this change), but it seems likely:
> Changed input API to allow bindings from a higher priority action set to suppress bindings from a lower priority action set when they both use the same input source.

I've attached the vrserver log:
[vrserver.txt](https://github.com/ValveSoftware/openvr/files/2076971/vrserver.txt)

**Comment by JoeLudwig** [comment] 2018-06-06 22:56
This should be fixed in the latest beta: https://steamcommunity.com/games/250820/announcements/detail/1657768916934266546

(It wasn't related to that app-side API change. It was caused by a driver-side API change that will be in a future SDK.)

**Closed by JoeLudwig** 2018-06-06 22:56 UTC

**Comment by walrus** [comment] 2018-06-07 10:12
Yeah, that fixes it. 👍 Any more information on this driver-side API change?
