### ISSUE TITLE
Empty screen when trying to configure the controller bindings for a vive tracker.

### ISSUE THREAD

**Issue by matzman666** [ValveSoftware/openvr#852] opened 2018-08-04 21:29 UTC
Whenever I try to configure the controller bindings for a vive tracker in the OpenVR controller bindings menu, I end up with an empty screen.

I open the controller binding settings via the dashboard, select a vive tracker, assign the "handed" role and the "right hand" role, then I want to open the page where I normally configure the individual buttons but end up with an empty page. Closing and re-opening the dashboard and the controller bindings page does not help.

**Comment by wirelessdreamer** [comment] 2018-08-05 18:47
I see the same behavior.

**Comment by JoeLudwig** [comment] 2018-08-06 17:43
When you say "empty screen" do you mean it's literally just an empty black screen? Does the header text and back button appear at the top?

Once you configure your tracker to be handed, does its icon get replaced with a generic looking handle with buttons + tracker, and does its name change to "Vive Tracker in Hand"?

Can you post a system report?

**Comment by matzman666** [comment] 2018-08-07 21:00
> Once you configure your tracker to be handed, does its icon get replaced with a generic looking handle with buttons + tracker, and does its name change to "Vive Tracker in Hand"?

Yes it does. That's how it looks like after I changed the tracker role to handed:
![Screenshot](https://user-images.githubusercontent.com/16060629/43801171-9c0b97ae-9a92-11e8-8018-a2126401f055.PNG)
And a new key representing the tracker is added to the "trackers" section in _steamvr.settings_ with the value "TrackerRole_Handed,TrackedControllerRole_RightHand".

But as soon as I press the "Edit" button for the current binding, I get a completely empty page that has no GUI elements whatsoever, it's only painted in the default SteamVR background color. And it affects the whole controller binding menu. When I close the dashboard, re-open it and go to "Settings" => "Controller Bindings" I always get an empty page.  It only goes away by restarting SteamVR.

Here's the system report: [SteamVRSystemReport.txt](https://github.com/ValveSoftware/openvr/files/2268004/SteamVRSystemReport.txt)

**Comment by wirelessdreamer** [comment] 2018-08-23 23:55
I just updated to the new beta, which among other issues said
![image](https://user-images.githubusercontent.com/140221/44557761-34ae0280-a70e-11e8-9186-1ed91abbe4e5.png)

Fixed tracker support in Tactical AR. Being the developer for Tactical AR, i can say its only half way there. button presses are sent to the tracker now, but an offset is always added to the tracker rotation, and trying to configure other orientations results in the empty screen error this bug was originally opened for.

**Comment by JoeLudwig** [comment] 2018-08-24 00:14
Are you sure you're using the default bindings that were added as part of that update? If you had existing edits you're probably using the old bindings plus whatever local edits you have. Try selecting the default binding from the binding list page.

The three fixes for Tactical AR were:

* Bind the trigger to also set the analog value to 1.0. (This fixed a bunch of other titles too.)
* Bind the "thumb" button to be both a trackpad click and an analog value on the bottom of the trackpad. It looked like the game was expecting a click on the bottom half of the trackpad.
* Add a new "pistol grip" pose option to the tracker and use that. The pose Tactical AR expected seemed to be rotated around an axis by about 30 degrees.

You can see the actual binding file in <steamvr>/drivers/htc/input/tracker/legacy_bindings_vive_tracker_tactical_ar.json

**Comment by wirelessdreamer** [comment] 2018-08-24 00:25
@JoeLudwig thanks, after updating to the beta today no pistol grip option showed up to me. I don't get to test the options much though because every time I select a new one the ui becomes fully unresponsive for me and I have to restart SteamVR. here is a video showing the issue start to finish hitting the Empty Screen: 
https://youtu.be/ugbyfkboeXg

**Comment by JoeLudwig** [comment] 2018-08-24 00:32
Can you post a system report so I can take a look at your logs?

**Comment by wirelessdreamer** [comment] 2018-08-24 00:42
[SteamVR-2018-08-23-PM_08_40_03.txt](https://github.com/ValveSoftware/openvr/files/2316631/SteamVR-2018-08-23-PM_08_40_03.txt)

and another troubleshooting video, pistol grip option definitely isn't showing up. https://youtu.be/PMfI4J1qczQ

**Comment by JoeLudwig** [comment] 2018-08-24 00:52
You're definitely getting the new bindings. That's why they have Tactical AR in the name. Pistol Grip is under this button:
![image](https://user-images.githubusercontent.com/303656/44559206-3de2a380-a6fd-11e8-9573-c8cc36a3fb4d.png)

Click the Pose Action button under there and you'll see the pose binding UI. It should have pistol grip set already.

**Comment by wirelessdreamer** [comment] 2018-08-24 01:17
Is this the right place? because i'm not seeing it here

![image](https://user-images.githubusercontent.com/140221/44559748-fa4a6280-a719-11e8-91ce-6dc360ace8b4.png)

**Comment by wirelessdreamer** [comment] 2018-08-24 01:30
the orientation of the controller is nowhere near where it was before the update, I looked in the json file you mentioned, but I don't see where i can update the controller offset in there so i can upload a proper file.

Is there a better place for back and forth on this. I don't want to hijack the issue this thread is on, originally it was related, but it no longer is the same issue. you can email me @ wirelessdreamer@gmail.com if that works for you.

**Comment by wirelessdreamer** [comment] 2018-08-24 12:08
I am still seeing some strange behavior. I'm in unity and have 1 vive
controller active, and 2 vive trackers active. in game i'm seeing 3 vive
controllers, and no trackers. is there a way in unity to show all devices
as what they really are, like before?

**Comment by dan-mirescu** [comment] 2018-09-03 22:52
I'm having the same black screen issue with the latest SteamVR beta (same issue before trying beta). I was trying to configure the default controller bindings for the Lucky's Tale game which is added in the library by Revive. (The game is an Oculus exclusive).
So for me the reproduction steps would be: Install SteamVR, install Oculus platform and Revive, install Lucky's Tale and click the button I highlighted here:
![image](https://user-images.githubusercontent.com/10550414/45002855-27cdc080-afe4-11e8-9a40-0f4bece6d4a2.png)

I tracked down the error to the same JS error which ctkjedi posted.
Manually changing the following in controllerbindingui<alphanumeric_string>.js
`for(var e=0,t=this.SelectedActionSetHaptics;e<t.length;e++)`
to
`for(var e=0,t=this.SelectedActionSetHaptics;t && e<t.length;e++)`
fixed it for me for all intents and purposes.

For the record, the file is in C:\Program Files (x86)\Steam\steamapps\common\SteamVR\resources\webinterface\dashboard and the actual filename can be seen in the browser dev tools.

**Comment by jackellenberger** [comment] 2018-11-06 17:44
@dan-mirescu How did you get steam to ingest that change? It seems like rebooting steam doesn't pull in the updated js file.

**Comment by glock00** [comment] 2018-11-09 18:06
> @dan-mirescu How did you get steam to ingest that change? It seems like rebooting steam doesn't pull in the updated js file.

Try "shift-F5" reload of the page or restart SteamVR after you made the change in the JS file. It worked for me. It's just not a solution for my problem though.

**Comment by captain-001** [comment] 2018-12-07 02:10
steamvr beta 1.1.4
Open binding UI in Unity
it's shown a black screen with 404 error.
http://localhost:8998/dashboard/localization/webhelper_koreana.json 404 (Not Found)
localiztion json file name should be changed korean.json instead.

ref:
SteamVR/resources/webinterface/dashboard/localization/bindingui_korean.json
SteamVR/resources/webinterface/dashboard/localization/webhelper_korean.json

**Comment by JoeLudwig** [comment] 2018-12-12 19:21
The korean language problem has been fixed and will be in the next beta update.

**Closed by JoeLudwig** 2018-12-12 19:21 UTC
