### ISSUE TITLE
Issues grow and don't get resolved, as more and more posts his very own issues...

### ISSUE THREAD

**Issue by TheWhiteAmbit** [ValveSoftware/openvr#462] opened 2017-04-06 14:31 UTC
There are issues were people don't know how to do a proper matrix multiplication or include header-files, and they don't close them even when they got helped. Does this really belong here, and serious issues don't get resolved because they keep unseen?!

Only way to fight this madness, seems to me though more madness...

**Comment by spayne** [comment] 2017-04-06 18:49
I think you can contribute good stuff and it'll evolve.

For example, one idea I'd like to do -- maybe you want to do it -- is to make a convincing report or blog on matrix math in openvr. It should explain when and why 4x4s and 3x4s are used and why quaternions are not used.  Show good ways to use these matrices in and out of opengl and unity.  Write a section on how the raw coordinate space is defined and mapped into other coordinate spaces (be specific and work through an example using an example room and lighthouse positions.  Show how this maps into standing, seated or relative spaces)  Show by example what IVRSystem::ApplyTransform does and if and how it determines new angular velocities and if/how it determines new accelerations.  Is it even performant?  How does openvr coordinate spaces and their transforms differ from what Oculus is doing?

**Comment by godbyk** [comment] 2017-04-06 19:38
I did get them to open [the wiki](https://github.com/ValveSoftware/openvr/wiki) for editing a while back. It might be helpful to start dumping information there.

**Comment by dashingstag** [comment] 2017-04-07 03:03
Isn't this committing the same problem that the author is suggesting? perhaps if there was a developer forum that people could be directed to...

**Comment by Balderick** [comment] 2017-04-07 07:45
> perhaps if there was a developer forum that people could be directed to...

https://steamcommunity.com/app/358720/discussions/
https://steamcommunity.com/app/507090/discussions/

**Comment by kalmiya** [comment] 2017-04-07 15:52
I understand the point you are making and your frustration, but you did sound kind of like a "know-it-all" Jerk in that other post.  That guy did actually give a good description of the issue (meaning I recognized it, because I made the same silly mistake, just spotted it quickly ^^ ) but sometimes people grow blind for their own code and just don't see it ( I sure did have that before ). So why not help out, took me a few seconds to reply. 

Concerning "more issues" - Valve _is_ looking into this forum and they are seen, but it appears they cherry-pick the things they want to fix and ignore other ones. I posted two related issues, one was picked up (within hours after posting, nice!) and the other is simply ignored (for >2 weeks now). Hardly can blame anyone other than the repo maintainer(s) for the growing list of "open and ignored"-issues. Most annoying is that the issue is actually a trivial feature-request and I'd add it myself if the SDK was OpenSource.

Also more samples might help - for fun compare OpenVR to the OculusSDK.

Either way, I think your point was made, so maybe worth closing this issue? :)

**Comment by eric-schleicher** [comment] 2017-04-13 08:14
should this issue be closed now ?

**Comment by JoeLudwig** [comment] 2017-04-13 20:37
Closing this. Because I hate irony. :)

**Closed by JoeLudwig** 2017-04-13 20:37 UTC

**Comment by TheDeveloperGuy** [comment] 2017-04-14 11:18
![17498795_436604693347433_1619893321498455866_n](https://cloud.githubusercontent.com/assets/22342164/25041996/c98ed2c0-2114-11e7-884e-0e9e7d7bf3b4.jpg)
