### ISSUE TITLE
sample hellovr_opengl errata

### ISSUE THREAD

**Issue by burito** [ValveSoftware/openvr#698] opened 2017-12-30 03:25 UTC
hellovr_opengl incorrectly calls glDisableVertexAttribArray() without a bound Vertex Array, this will cause a GL_INVALID_OPERATION.

Fix provided https://github.com/ValveSoftware/openvr/pull/696

**Comment by kisak-valve** [comment] 2017-12-30 14:02
Hello @burito, there's no need for a separate issue report to go with a pull request. Closing as a duplicate of #696.

**Closed by kisak-valve** 2017-12-30 14:02 UTC
