### ISSUE TITLE
Different IVROverlay for each eye.

### ISSUE THREAD

**Issue by adamroszyk** [ValveSoftware/openvr#521] opened 2017-05-18 09:46 UTC
Hi,
is it possible to render two different overlays for each eye separately?
I thought that it's as simple as changing Layer for Overlay object and then setting proper Culling Mask to each Eye- but it doesn't seem to have any effect.

Do you have any suggestion what could I do to achieve it?

Thanks !

**Comment by Hotrian** [comment] 2017-06-12 00:01
Hello!

If you combine the left and right textures into a single texture (such as [side by side 3d](https://www.google.com/search?q=side+by+side+3d&source=lnms&tbm=isch)), you can do this:

````
var overlay = OpenVR.Overlay;
if (overlay == null) return;

ulong _handle;
var error = overlay.CreateOverlay("foo", "bar", ref _handle);
if (error != EVROverlayError.None)
    return;
[...]

// Enable 3d Side By Side
overlay.SetOverlayFlag(_handle, VROverlayFlags.SideBySide_Parallel, true);
````

This will feed the left half of the supplied texture to the left eye, and the right half to the right eye. I'm not sure why you'd want to do this unless you were doing some sort of side-by-side 3d Overlay, but either way this will still work even if you are just trying to send a different texture to each eye.

To turn it off, you of course just need to pass `false` instead of `true`:

````
// Disable 3d Side By Side
overlay.SetOverlayFlag(_handle, VROverlayFlags.SideBySide_Parallel, false);
````

Additionally, in my testing, I found that the `SideBySide_Crossed` flag did not work (this may be fixed now in the latest API, not sure). However, incidentally I discovered if you set the `SideBySide_Parallel` flag, and in addition set the `Curved` flag, you would get the intended result - the left and right eye channels are swapped (in case the source texture is packed in reverse).

````
// Enable Crossed 3d Side By Side (SideBySide_Crossed flag not working properly)
overlay.SetOverlayFlag(_handle, VROverlayFlags.Curved, true);
overlay.SetOverlayFlag(_handle, VROverlayFlags.SideBySide_Parallel, true);
````

The final result is something like this:

````
switch (SideBySide)
{
    case SideBySideMode.None:
        overlay.SetOverlayFlag(_handle, VROverlayFlags.Curved, false);
        overlay.SetOverlayFlag(_handle, VROverlayFlags.SideBySide_Parallel, false);
        break;
    case SideBySideMode.Regular:
        overlay.SetOverlayFlag(_handle, VROverlayFlags.Curved, false);
        overlay.SetOverlayFlag(_handle, VROverlayFlags.SideBySide_Parallel, true);
        break;
    case SideBySideMode.Crossed:
        overlay.SetOverlayFlag(_handle, VROverlayFlags.Curved, true);
        overlay.SetOverlayFlag(_handle, VROverlayFlags.SideBySide_Parallel, true);
        break;
    default:
        throw new ArgumentOutOfRangeException();
}

[...]

public enum SideBySideMode
{
    None = 0,
    Regular,
    Crossed,
}
````

Of course, you have to watch out for the case where you're using a High Quality overlay, with `Curved` and `SideBySide_Parallel` enabled - I'm not sure I tested to see the outcome on this one, since I was not using High Quality Overlays in my project.

**Comment by fragmentvr-dev** [comment] 2018-10-05 14:19
@adamroszyk did you manage to solve this?

**Comment by fragmentvr-dev** [comment] 2018-10-12 08:37
@Hotrian Do you know how to account for IPD in a Side By Side Overlay? I've got it set up but it's noticeably and painfully not calibrated correctly causing the user to go cross-eyed.

**Comment by Hokage3211** [comment] 2019-12-27 00:53
Hello, commenting on this issue in an attempt to avoid creating new issues, but also to bring new research; the "side_by_side_crossed" as far as I can tell simply reverses the eyes, and parallel is what you'd expect, normal SBS 3D, unfortunately I'm running into a problem where the overlay is not handling the rapidly updating texture very well, it's giving artifacts and stuttering badly, but only ever on the right half of the texture (ie: the right eye), the left half runs smoothly and perfectly with only sometimes artifacts. 

I've managed to isolate it to something steamVR is doing because I've tried swapped cameras, swapped render textures, tried rendering only one eye, one camera, swapping positions in hierarchy, even manually controlling when the cameras render and when the pose is updated, it's always the right eye that has major problems, stutters, lags, and has tears along it. Also to note: setting the overlay to the "side_by_side_crossed" flag still has the right eye have these problems, giving more of an indication that it's something to do with internals of steamVR. 

I'm potentially using an older version of the code, but I had to manually fix the overlay to work as a standalone application in the first place (using hotrian's and others' research and pull requests), so I can't just update steamVR to test it, and unsure where the deeper drivers are, to update them.

Any ideas? Help? Advice? I'd appreciate anything anyone can give.

**Comment by JoeLudwig** [comment] 2019-12-27 00:58
@Hokage3211 You should open a new issue. If you have a sample app that reproduces the problem, that would help.
@fragmentvr-dev (I realize this was from a year ago at this point, so it may no longer matter.) The stereo overlays just show the left side in the left eye and the right side in the right eye. Any adjustment for IPD is up to whatever is generating those textures.

@adamroszyk 's question was answered, so I'm closing this one.

**Closed by JoeLudwig** 2019-12-27 00:58 UTC
