### ISSUE TITLE
Alternate binding mgmt needed - Bindings for Revive based game not consistently saved/presented

### ISSUE THREAD

**Issue by zxsdklfhskyrvk** [ValveSoftware/openvr#1226] opened 2019-10-27 17:42 UTC
I'm just a user,  but I'm sick of the terrible binding support issues on this topic.  The bindings I am presented for a game (like The Climb used via Revive) varies without any clear pattern.  Some days it will have the defaults.  Some days it will show my previously created bindings.

This issue continues in steamvr 1.8.16 - and I have created brand new bindings as well as attempted to delete the old "unsupported" bindings.  Only to have my new ones "disappear" and the old ones presented, at next login.

Are the bindings for non-steamvr games not being properly cached/uploaded into Workshop because they lack proper IDs or something?  I suspect something is determining the need to refresh my local bindings from the server, without first uploading my new ones.

But I could be clueless.  Regardless, this is a major failure for the bindings and I'm tired of dealing with it.  Index user here.

**Please help by documenting a method for reviewing, backing up and restoring bindings directly on local PC - separate from the unusable system in place.  I don't even care if the issue is ever fixed if I can script my own one-time fix.**

**Comment by JoeLudwig** [comment] 2019-10-28 18:04
Can you post screenshots (or even the text) of the errors you're getting? A system report would help too.

The binding system doesn't care if the game came from Steam, and Revive provides the necessary app keys for things to work. There were some bugs in the way the binding system dealt with its internal version numbers, but those should have been fixed in 1.8.16.  The fix did require saving every binding again, so it might have caused you to lose your bindings one more time before it was resolved.

**Comment by JoeLudwig** [comment] 2019-10-30 01:34
If you're still having this issue with 1.8.17 and beyond, please reply here and I'll reopen the bug.

**Comment by zxsdklfhskyrvk** [comment] 2019-10-30 01:34
I appreciate the response.  There is no error.  It simply reverts to a previous set of bindings (multiple) I had created previously.  I will say that I've edited them from inside VR, as well as on the desktop,  as well as using the direct localhost url.  I wonder if those various methods lead to different results/sets.

Given the random experience I've had with bindings presented, I'm not sure I can reliability test,  unless I do it over a longer period.  Which is why I'm keen on just learning how to backup what I want.

**Closed by JoeLudwig** 2019-10-30 01:34 UTC

**Comment by JoeLudwig** [comment] 2019-10-30 20:37
The dashboard, desktop, and your own browser all run the same code, so I would be very surprised if there were a difference in bindings reverting caused by that.

If you turn on this option in the Developer options you will gain an export button in the binding UI that will write the binding files to your Documents directory: 
![image](https://user-images.githubusercontent.com/303656/67896625-f84c1280-fb19-11e9-8148-cb6782b15b3c.png)

If you put binding files in <documents>/steamvr/input/imports they'll start showing up in the binding list so you can move bindings the other way.

Be aware that these debugging options are intended for developers and the UI isn't particularly pretty.  The best option would be to fix the bug that's causing you to lose bindings. Posting a system report would help us do that.

**Comment by zxsdklfhskyrvk** [comment] 2019-12-23 03:20
Its been awhile,  but I'm trying to play a game (Talos Principle VR),  and no matter what I do in the bindings UI,  it resets any custom binding I create.  Is this an option possible for a developer to perform? (a forced binding?)

![talos principle Index binding issue](https://user-images.githubusercontent.com/51089832/71333725-1d04ab00-2509-11ea-8679-b673b8f70ca1.png)

![Talos principle binding in strange folder seems to prevent any changes](https://user-images.githubusercontent.com/51089832/71333701-03fbfa00-2509-11ea-993f-f9d65a2c066f.PNG)

 
I ALSO saw it "recreate" bindings I had deleted a few minutes before.  This could be caused by some data sync issue in the app.  But the fact is I deleted the bindings, and they reappeared.

**Comment by JoeLudwig** [comment] 2019-12-23 03:39
Can you post a system report, please? You'll find it on the SteamVR menu in the status window.

**Comment by zxsdklfhskyrvk** [comment] 2019-12-23 03:48
System report
[SteamVR-2019-12-22-PM_10_47_59.txt](https://github.com/ValveSoftware/openvr/files/3993569/SteamVR-2019-12-22-PM_10_47_59.txt)

**Comment by zxsdklfhskyrvk** [comment] 2020-01-20 17:06
Is there any chance of getting a response on this @JoeLudwig ?

**Comment by zxsdklfhskyrvk** [comment] 2020-03-06 15:53
Just for the record,  this was just fixed in update SteamVR 1.10.23 and possibly 1.10.24.
