### ISSUE TITLE
Compositor_StageRenderSettings structure and VS2013

### ISSUE THREAD

**Issue by SDraw** [ValveSoftware/openvr#1281] opened 2019-12-31 12:03 UTC
After latest release compiler of VS2013 throws errors
```
error C2797: 'vr::Compositor_StageRenderSettings::m_PrimaryColor': list initialization inside member initializer list or non-static data member initializer is not implemented
error C2797: 'vr::Compositor_StageRenderSettings::m_SecondaryColor': list initialization inside member initializer list or non-static data member initializer is not implemented
```
on [these lines](../blob/master/headers/openvr.h#L3110-L3111). Obviously, compiler wasn't made for this type of initialization at that time. 
What can be done on my side to use SDK without manual editing of these lines?

**Comment by SDraw** [comment] 2020-01-10 14:18
Turns out this is a problem of VS2013: https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c2797?view=vs-2019

**Comment by TheDeveloperGuy** [comment] 2020-01-10 15:13
Wrong answer. If I have to edit the header files to make them work with 2013, when they did before without editing, it is a problem in OpenVR SDK. Unless support for VS2013 has been dropped from the OpenVR SDK, in which case, it seems a bit rash just because whoever added the new structure to the header file can't be bothered to retain backwards compatibility.

**Comment by SDraw** [comment] 2020-01-10 18:13
Alright, let's wait an answer about it from devs.

**Comment by TheDeveloperGuy** [comment] 2020-01-10 19:04
As a temporary fix I edited the initialisers out of the header file. I'm not using that structure anywhere, so it's fine to use it like that for now.

**Comment by echuber2** [comment] 2020-01-10 19:48
Instead of editing them out entirely, you could add a default constructor and initialize the members there with the same values.

**Comment by TheDeveloperGuy** [comment] 2020-01-10 20:02
Yes, that would be the way to fix it properly. Hopefully Valve can do that for next release.

**Comment by echuber2** [comment] 2020-01-10 20:06
I mean, anyone can do it themselves right now if they still need to compile on a very old compiler. Although, it's not clear that a compiler version nearly a decade old will be fully compatible with the binary part of the SDK even if editing the headers gets it to compile.

**Comment by TheDeveloperGuy** [comment] 2020-01-10 20:34
It seems unnecessary to break support for VS2013 over 1 structure that can easily be fixed. Some drivers need to be built with VS2013 due to changes in the VC runtime in VS2015+ that don't allow static libraries built with earlier versions. Everything was working fine until this structure was added.

**Comment by aleiby** [comment] 2020-01-10 23:48
This was an oversight.  We use C++11 internally, but that should not have leaked into the public headers.  I'll fix this up in the next update.  In the meantime, the easiest thing would be to simply strip them out of your local copy.

**Comment by TheDeveloperGuy** [comment] 2020-01-11 15:42
@SDraw You can probably close this again. It's been assigned in (and is a duplicate of):

https://github.com/ValveSoftware/openvr/issues/1288

**Closed** 2020-01-11 17:31 UTC
