### ISSUE TITLE
ViveInput breaks when AppMenuButton is pressed under Linux (openvr 1.0.12)

### ISSUE THREAD

**Issue by Nyran** [ValveSoftware/openvr#736] opened 2018-02-01 13:39 UTC

**Comment by JoeLudwig** [comment] 2018-02-01 16:56
I don't know what ViveInput is. 

Maybe you can provide some details about what you're seeing? What hardware is installed? What sort of app is making the call? Is the dashboard visible?

**Comment by Nyran** [comment] 2018-02-01 17:29
Sorry, next time I should double check what I am writing. 

Currently we are using openVR 1.0.12 in combination with the HTC vive in our rendering engine both under windows and linux (in this case Ubuntu 16.04 LTS). The retrieval  poses (HMD, two controllers, two lighthouses) works flawless, just as almost all of the button states. The only exception is the app menu button of the controllers. It appears, that pressing this button effectively causes the controller button states to not be forwarded properly anymore. On second consideration, this might be rather a problem with SteamVR under Linux. 

The dashboard is not visible. Do you need details about the PC hardware?

Right now the issue is not too much of a big deal as long as I remember not to press the app menu button. 

If you consider this problem to be rather related to steamVR instead of openVR, feel free to close this issue.

Best regards
Adrian

**Comment by JoeLudwig** [comment] 2018-02-01 17:47
When you say "app menu button" you mean the one with the cheeseburger icon at the top of the controller, right?  That's strange...

PC hardware shouldn't matter much. If you could provide a system report that would help me check a few things.

**Comment by Nyran** [comment] 2018-02-01 18:06
![app_menu_button](https://user-images.githubusercontent.com/7204260/35694689-573b1e22-0782-11e8-9ebe-95e14feb5e58.jpg)

I marked the button I am referring to in the attached image with a red circle. I think this Is the app menu button, not sure though. But in any case, if this button is pressed under Linux, I need to reboot the PC to get the Input forwarded properly again. By the way, what actually happens after I pressed the button (and which does not change until I actually reboot the PC), is that **GetControllerState** called on our instance of  **vr::VRControllerState_t** returns false, although the VRControllerState_t instance is valid and the device idx for the controller is valid as well.

What exactly do you want me to send you when you say system report?

**Comment by Nyran** [comment] 2018-02-02 09:22
Hi @GimpMaster,
this is actually interesting. I think it is reasonable that only a reboot fixes my problem in this case, if I am actually breaking the (already pretty stable, but not quite perfect) steamvr client on linux. I was actually not too aware of the openvr keys and therefore also not the "sendSystemButtonToAllApps"-key, but I will check if the behaviour changes if I set the corresponding attribute to false. I would be extremely satisfied already, if steamvr would not crash if someone accidentally presses the button. Thank you very much for the information. I will edit this message after I tried out changing the attribute.

**Comment by Nyran** [comment] 2018-02-02 13:20
Unfortunately, setting the "sendSystemButtonToAllApps" option to false in the VRSettings object did not prevent the input processing from breaking.

**Comment by GimpMaster** [comment] 2018-02-02 16:38
@Nyran are you using the steamVR beta? 

In the windows version using the NON-BETA if you disable VR dashboard and click the system menu button all input will stop. It doesn't matter if you have the sendSystemButtonToAllApps. It just breaks the controller input until you restart SteamVR. You do not need to restart your whole computer. (Again this is in windows).

This has been this way since January 5th.

Unfortunately like I said even the Beta is not back to the way it was in Dec 2017. Hopefully Valve developers will fix it back to the way it was.

**Comment by Nyran** [comment] 2018-02-02 18:02
@GimpMaster no, I am not using the beta, but I am working on linux.
I guess here the symptom is similar and restarting SteamVR would technically work as well, although it appears to not be as stable as on Windows, such that in the end I end up restarting the PC. This helps me because we are booting from an LTSP linux and I basically quickly install steam everytime I reboot my PC and it works flawless again. Restarting SteamVR (even including a restart of Steam) does not work properly on Ubuntu 16.04 LTS at this point in time. 

Nevertheless, I think I will just wait until there is an update of SteamVR/OpenVR fixing this issue. Most of the functionality is working pretty well across different operating systems so far, so I am more or less satisfied right now. Thank you nevertheless for the discussion!

**Comment by JoeLudwig** [comment] 2018-02-03 00:29
@nyran That's the system button. There's a bug in the non-beta build (fixed in the beta) that takes away input when somebody hits that button, even if the dashboard is disabled. 

There's an unrelated bug that @GimpMaster is running into if you want to use the system button for something else in an arcade or other situation where you control the PC. We have a fix for that too, and it will be in the next SteamVR beta update. We just didn't get it done quite in time for today's update.

Both of these will roll out to everyone in the next week or two. For now you'll need to opt-in to the beta.

**Closed by JoeLudwig** 2018-02-03 00:29 UTC

**Comment by GimpMaster** [comment] 2018-02-03 04:49
@JoeLudwig - That is great news.

**Comment by yegors** [comment] 2018-02-12 16:10
None of the recent updates have fixed the intermittent issues related to sendSystemButtonToAllApps @GimpMaster  mentioned. Is there an ETA for a fix?

**Comment by JoeLudwig** [comment] 2018-02-12 22:43
@yegors The system button is no longer intermittent for me when opted-in to the beta with sendSystemButtonToAllApps set. Can you post a system report while you're reproducing the problem?

**Comment by GimpMaster** [comment] 2018-02-12 22:45
I agree with Joe....try the newest beta and it works good. 

Joe what is your thoughts on the mouse input for background applications?

**Comment by yegors** [comment] 2018-02-12 22:49
I have the latest beta from Feb 9th, the behavior is identical to the previous versions. It takes 1-5 clicks for the event to be registered, and therefore hooked into. 

https://zerobin.net/?672936e08dff4303#WKr2ZWKE2v+BlyX3IqlPB7nDndq6fjPVsDyWuUa/U3Y=

**Comment by JoeLudwig** [comment] 2018-02-12 22:49
That one's not so much about background applications as it is about mouse input for overlays when the dashboard isn't up. That's a case that sort of worked by accident before but isn't currently supported in the new input system.

It's on my list, but I don't know exactly when it'll show up. It will probably be something like the keyboard over an app when it does. If you point your controllers at such an overlay they'll take over input, draw the controllers, draw the laser pointer, etc.

**Comment by GimpMaster** [comment] 2018-02-12 22:58
Joe - Dang. I was afraid of that. Can you think of any other method to achieve near the same result. I suppose I can get the control pose and draw a circle on the overlay dynamically. 

Are they ray cast tests against overlays?

Also when do you think you will merge beta into release?

**Comment by JoeLudwig** [comment] 2018-02-12 23:00
Beta into release is likely in the next few days. 

There's a fairly complicated state machine involved in running the laser mouse. It casts rays against the overlays, but does a bunch of work to make sure that mouse ups go to the right overlay, to transition from overlay to overlay, etc.

**Comment by GimpMaster** [comment] 2018-02-12 23:11
All I really care for is an UV value 0-1 where it intersects my overlay. I can take care of the rest. It doesn’t even need to be a mouse event. Anything like that in openvr SDK?

**Comment by bddckr** [comment] 2018-02-13 09:40
@GimpMaster This should work:
https://github.com/ValveSoftware/openvr/blob/53c417bb16cee003cd949254a2aa00714046efbd/headers/openvr.h#L3025-L3027
