### ISSUE TITLE
Companion window view is upside down in sample hellovr_opengl

### ISSUE THREAD

**Issue by cmbruns** [ValveSoftware/openvr#1142] opened 2019-06-24 03:24 UTC
Steps to reproduce:

1. Build and run hellovr_opengl program in the samples folder.
2. Hold one of the controllers upright directly in front of the HMD.
3. Notice in the companion view window on your monitor in regular reality, the view is flipped top to bottom. It should probably be right-side-up.

**Comment by kisak-valve** [comment] 2019-06-24 12:16
Closing as a duplicate of #1113.

**Closed by kisak-valve** 2019-06-24 12:16 UTC

**Comment by cmbruns** [comment] 2019-06-24 16:46
Can an issue duplicate a pull request? I suppose when you've got 600 open issues it's tempting to "always be closing".
