### ISSUE TITLE
IVRServerDriverHost::SetRecommendedRenderTargetSize does not work in 1.18

### ISSUE THREAD

**Issue by risa2000** [ValveSoftware/openvr#1568] opened 2021-07-22 10:56 UTC
This just a reiteration of #1445, in a hope to get an attention:

`IVRServerDriverHost::SetRecommendedRenderTargetSize` does not correctly change the `width` and `height`.
When the driver calls the function with, for example, `width=2867, height=1959` and the the client app calls `IVRSystem::GetRecommendedRenderTargetSize` to get the new recommended values the API returns `width=1959, height=1959`.

It seems like new `height` is copied to `width` and the `height` is preserved as well.
The app (if it supports the dynamic recommended render target res) visually works, but runs with wrong render resolution as it is impossible to set a new `width`.

**Comment by kisak-valve** [comment] 2021-07-22 11:21
Hello @risa2000, please do not intentionally create duplicate issue reports.

Closing as a duplicate of #1445.

**Closed by kisak-valve** 2021-07-22 11:21 UTC

**Comment by risa2000** [comment] 2021-07-22 13:38
I appreciate your attention, but it is unfortunately not where I would expect it. The function in question was introduced in 1.14 (IIRC) as a new feature (support) for the driver, and right after the release was signaled as not working (which is a problem because you need it to work for the other function introduced in 1.14 related to FOV change) by @TheDeveloperGuy. I bumped the problem 3 months later, expecting the fix ASAP as it seems to be just some kind of typo somewhere. 10 months later we are here discussing not duplicating the issues.

**Comment by TheDeveloperGuy** [comment] 2021-07-22 13:58
@risa2000 Welcome to OpenVR/SteamVR development. Counter-intuitively (as it is by far the most used VR runtime in the world) most bug reports are ignored, and a ridiculous amount of bugs slip into each release. Even show-stoppers, which would definitely beg the question of how good their QA is. I don't even bother any more, as it's a waste of my time. I've learned that one has to work around the bugs in the software, anything else will lead to madness.

**Comment by TheDeveloperGuy** [comment] 2021-07-22 14:03
@risa2000 I expect part of the problem is that many developers use the issue reporting as a support forum, and not for reporting issues. There is a lot of noise here, and there probably should have been (far too late now) a separate developer support forum.
