### ISSUE TITLE
BUG: SteamVR 2.0/2.1 does not show overlay thumbnail

### ISSUE THREAD

**Issue by TheDeveloperGuy** [ValveSoftware/openvr#1788] opened 2023-11-08 11:42 UTC
In SteamVR Dashboard, an overlay can set its dashboard icon/thumbnail, via vr::VROverlay()->SetOverlayTexture(), using the texture handle created via vr::VROverlay()->CreateDashboardOverlay(). 

This has always worked for every SteamVR release, until now. Whether or not the overlay sets the thumbnail texture, it is never displayed, and a placeholder image '?' is used instead. 

There is a new event in the OpenVR 2.0 SDK, that may be related, but as usual the absolute lack of documentation or relevant code samples means that it must be guessed whether this is sent to or from a VR application or driver and what its event data might be:

VREvent_DashboardThumbChanged

**Comment by kisak-valve** [comment] 2023-11-08 13:21
Hello @TheDeveloperGuy, this issue is already being tracked at #1785.

Closing as a duplicate.

**Closed by kisak-valve** 2023-11-08 13:21 UTC

**Comment by TheDeveloperGuy** [comment] 2023-11-08 14:04
> Hello @TheDeveloperGuy, this issue is already being tracked at #1785.
> 
> Closing as a duplicate.

It has a very direct impact on perceived quality. Why is a fix "not planned"? What is the use case for "VREvent_DashboardThumbChanged"?

**Comment by kisak-valve** [comment] 2023-11-08 14:11
Friendly reminder that I'm a moderator for Valve's issue trackers on Github, and not a SteamVR developer myself. We'll need to hear from a SteamVR dev for your more detailed questions.

> Why is a fix "not planned"?

The choice of wording is Github's not mine, with the tool tip that that is used with issues that won't be fixed, can't reproduce, duplicate, or stale.

**Comment by TheDeveloperGuy** [comment] 2023-11-08 14:32
Got, thanks for replying!

**Comment by TheDeveloperGuy** [comment] 2024-02-20 17:14
RESOLVED: The change in behaviour that was introduced with SteamVR 2.0 is:

Overlay key cannot include spaces.

This is what is causing the icon behaviour. Previous versions of SteamVR didn't have this behaviour. Everything else works correctly. Fix (in lieu of SteamVR fix) is to not include spaces in overlay key.
