### ISSUE TITLE
Will new OpenVR Unity XR plugin work for other Unity VR platforms?

### ISSUE THREAD

**Issue by dpggit** [ValveSoftware/openvr#1312] opened 2020-02-15 14:46 UTC
I have read this https://blogs.unity3d.com/es/2020/01/24/unity-xr-platform-updates/ and if i understood well if i make a game with the new OpenVR Unity XR plugin it will work for any other platform Unity supports like PSVR ,Mixed reality or Occulus?
And could you tell me about when this plugin could be released? 
And all steamvr scene examples will be updated to the new plugin?

**Comment by bddckr** [comment] 2020-02-20 18:25
@kisak-valve Duplicate of https://github.com/ValveSoftware/steamvr_unity_plugin/issues/655

**Comment by kisak-valve** [comment] 2020-02-20 18:27
Closing per the last comment.

**Closed by kisak-valve** 2020-02-20 18:27 UTC
