### ISSUE TITLE
Motion compensation once again

### ISSUE THREAD

**Issue by SeriouSerg** [ValveSoftware/openvr#1444] opened 2020-09-20 22:56 UTC
Hi! 
And once again I appeal to the responsible persons from Valve - are you thinking about native support for **motion compensation?**
If not, then this is very strange and sad, because motion rigs +VR is the future that comes very quickly.
There is **only one working solution for motion compensation for the whole world**, and every time you update SteamVR, everything collapses.
**Is it difficult to add 200 lines of code?** Why the single person can make it, but the huge company did not and will not?
The entire community of motion rig owners would like to hear official comments on this question. Thanks if you heard us.

**Comment by kisak-valve** [comment] 2020-09-20 23:05
Helo @SeriouSerg, please do not open duplicate issue reports. There's no value in fragmenting the discussion over multiple issues.

Closing as a duplicate of #1419.

**Closed by kisak-valve** 2020-09-20 23:05 UTC
