### ISSUE TITLE
Massive lag spike every 8 seconds - reproducible

### ISSUE THREAD

**Issue by JChief** [ValveSoftware/openvr#401] opened 2017-02-12 16:51 UTC
Issue: If connected to Wifi wirelessly and using a USB dongle (most of you), every 8 seconds or so when using either Vive Home, Revive, OR Advanced Settings (2.0 as well), you will experience a massive lag spike (intermittently spiking from 18-23ms to over 2-3000ms for me). Adding ANY extensions to the SteamVR dashboard when using the Vive causes network issues when SteamVR beta is running.

Reproduction steps:

Install PingTracer for monitoring, set host to iad.valve.net (Steam's east coast game server), and click Start. You can get PingTracer here: https://pingtracer.codeplex.com/ (To rule out an issue with iad.valve.net, you can also ping Google.com if you prefer).
(Ensure Revive - 1.0.4 is installed) Start SteamVR.
Note that every 8 seconds you will receive a latency spike near 200ms (see the yellow bars in the graph here: http://imgur.com/J8VMiTR). This should start within 8 seconds of the Lighthouses detecting the HMD. The controllers do not need to be turned on for the lag spikes to happen.
Quit SteamVR - notice the graph in PingTracer returns to normal.
Uninstall Revive 1.0.4.
Launch SteamVR - notice there are no more lag spikes. As you can see here, at 3:44PM I uninstalled Revive, then opened SteamVR. No more latency spikes.
To make the lag spikes appear again, quit SteamVR, reinstall Revive 1.0.4, and restart SteamVR. Within 8 seconds the same lag spikes appear.

Impact: Makes all VR multiplayer go from inconsistent to virtually unusable due to these intermittent lag spikes (Smashbox, Raw Data, QuiVR, etc)
Try it yourself by running a constant ping (ping -t if on Windows) to a public IP (8.8.8.8 for example)
Recently this was reported to the Revive devs, but they believe it is in the SteamVR software itself: https://github.com/LibreVR/Revive/issues/466
Also this was posted to the Open VR GitHub issues page: https://github.com/ValveSoftware/openvr/issues/374

**Comment by kisak-valve** [comment] 2017-02-13 13:45
Closing as a duplicate of #374.

**Closed by kisak-valve** 2017-02-13 13:45 UTC
