### ISSUE TITLE
TriggerHapticPulse hanging SteamVR

### ISSUE THREAD

**Issue by jrbudda** [ValveSoftware/openvr#391] opened 2017-02-05 07:20 UTC
Kind of a huge problem. One other person at least has seen it http://steamcommunity.com/app/358720/discussions/0/133256240733525666/

What I'm seeing is any haptic pulse call has a tiny possibility of getting SteamVR into some weird state. While in this state the call to WaitGetPoses will take ~100ms to return and returns error 101 (DoNotHaveFocus). The subsequent .submit call fails with 'AlreadySubmitted;. Brings the game down to about 8 fps. 

If I trigger another haptic pulse, it fixes it instantly. If I do not trigger another pulse, it will remain this way until the game is closed.

Let me know if there's more info I can provide to help. Beta Branch, using 1.0.5 wrapper.

Edit: from vrserver.txt  http://pastebin.com/miP5AsLX
This starts the issue: 
Sun Feb 05 2017 03:17:37.848 - Unknown message type Unknown VRMsgType (1049352) (419430400 byte payload) from javaw (20968). Disconnecting.

When I trigger another pulse to unstick it:
Sun Feb 05 2017 03:19:52.368 - New Connect message from C:\Program Files\Java\jdk1.7.0_79\bin\javaw.exe (VRApplication_Scene) (Args: -[Removed]
03:19:52.368 - Creating builtin app for C:\Program Files\Java\jdk1.7.0_79\bin\javaw.exe (VRApplication_Scene)
Sun Feb 05 2017 03:19:52.372 - Setting app system.generated.javaw.exe PID to 20968

and vrclient_javaw.txt
Sun Feb 05 2017 03:17:38.066 - Application submitted two left scene textures for a single frame!
Sun Feb 05 2017 03:17:38.066 - Application submitted two right scene textures for a single frame!
Sun Feb 05 2017 03:19:52.257 - IPCPipe(VR_ServerPipe): Waiting on event failed in SendMessageInternal with res 0 and error 232
Sun Feb 05 2017 03:19:52.372 - Received success response from vrserver connect
Sun Feb 05 2017 03:19:52.372 - Successfully reconnected to server

**Comment by McKay42** [comment] 2017-02-05 11:37
Valve, please fix

I could also provide logs, or even a minimal test application which causes the bug(s).
Not sure where the chances of someone noticing this are higher, on the Steam forums or here?

**Comment by jrbudda** [comment] 2017-02-08 03:40
Both McKay42 and I are using OpenGL and directly calling OpenVR, if that helps.

**Comment by McKay42** [comment] 2017-02-08 11:23
After further tests, it seems that the bug is caused by sending a TriggerHapticPulse() to *both* controllers within the *same* frame (with *no* executions of WaitGetPoses() inbetween).

Something like this will break it almost instantly constantly (using a 100 ms delay per call):
```C++
float nextHapticPulseTime = 0.0f;

// assume that onUpdate() is called 90 times a second
void onUpdate()
{
    if (currentTimeInSecondsFloat() > nextHapticPulseTime)
    {
        nextHapticPulseTime = currentTimeInSecondsFloat() + 0.1f;

        m_pHMD->TriggerHapticPulse(leftControllerIndex, 0, 1000);
        m_pHMD->TriggerHapticPulse(rightControllerIndex, 0, 1000);
    }

    ...
    m_pHMD->WaitGetPoses( ... );
    renderScene( ... );
    ...
}
```

**Comment by McKay42** [comment] 2017-02-08 12:11
Workaround:
Only allow 1 controller to directly execute TriggerHapticPulse() within one iteration of WaitGetPoses(), buffer all other calls of the second controller and only execute them in the next frame (when it's the second controller's turn).

It hasn't happened once since I added this workaround (even with the code in my previous comment), although I still have to playtest a bit longer to really confirm it.

**Comment by McKay42** [comment] 2017-03-04 18:04
And we have a Unity rhythm game where the same bug happens: https://www.reddit.com/r/Vive/comments/5xgpza/i_made_a_little_rhythm_game_where_you_can_create/

So it's _not_ due to 32 bit dlls or raw OpenVR API usage in C++.
It just simply doesn't occur too often in games which don't trigger pulses in regular intervals, that's why it's especially noticeable in rhythm games.

**Comment by jukibom** [comment] 2017-06-11 23:41
This also appears to be affecting a bunch of other games, most notably [Audioshield's pretty large thread](https://steamcommunity.com/app/412740/discussions/0/1318836262651659474/) (as you say, it's pretty haptic-heavy). This is a seriously rough bug.

**Comment by foundway** [comment] 2017-06-14 20:20
Our game is also suffer from this issue. Hope Valve can have a solution or workaround soon.

**Comment by jukibom** [comment] 2017-06-20 18:43
Is this now fixed? https://steamcommunity.com/games/250820/announcements/detail/3062859752422616729

> Fixed bugs related to “pipe disconnections” in certain games on certain user machines. One way this would manifest is that haptic feedback would stop working, but sometimes it appeared as general instability in SteamVR.

**Comment by JoeLudwig** [comment] 2017-06-20 21:43
Significant changes were made to the way SteamVR uses named pipes on Windows with the goal of making them more reliable. If you were affected by this issue, please see if your issues are fixed in the beta.

We could never reproduce this problem reliably, so we can't verify that it fixed any particular bug.

**Comment by jukibom** [comment] 2017-06-20 21:54
From my limited experience today it seems to be fixed, at least in the case of Audioshield. Hopefully others who can reliably reproduce it will post back. 

Thanks :D

**Comment by McKay42** [comment] 2017-06-21 16:50
Thanks, finally!
It hasn't happened once since the update, even in equal worst case scenarios. Still needs more time to validate completely though since it was very random, I'll keep testing during the next few days.

**Comment by JoeLudwig** [comment] 2017-06-21 18:27
Glad it seems to be fixed. Let's call this closed for now. If you run into this again, please let us know.

**Closed by JoeLudwig** 2017-06-21 18:27 UTC
