### ISSUE TITLE
Unable to save binding for background applications or applications not distributed to steam.

### ISSUE THREAD

**Issue by peroht** [ValveSoftware/openvr#1193] opened 2019-09-13 13:47 UTC
_Edited: I have a temporary solution for this bug. Check my comment further down._

When building a project using Unity (2018.3.0f2) with SteamVR Unity Plugin v2.3.2 (sdk 1.4.18) I am able to save and generate action/binding files. Still inside Unity, when I press "Open Binding UI" I am able to edit my application. When I press "Save Personal Binding" I get a successful save result and can continue the configuration process.

However, when I build the application to an exe, and run it locally and try to do the same thing, pressing "Save Personal Binding" stalls and the UI says "Uploading...". 

Interestingly, pressing "Replace Default Bindings" seem to work and I get a record in the steam.vrsettings file. But "Save Personal Bindings" does not work at all for me. I have tried two accounts and a total of 4 different machines, with same result.

I have tried this with another of my background applications (c++) and it fails as well. 

I have tried this with a (legacy) game that has worked since may last year and it fails as well.

When I choose a game e.g. The Lab I am able to press "Save Personal Binding" without a problem. 

SteamVR 1.7.15 (main and beta same problem). 

[SteamVR-2019-09-13-PM_03_41_57.zip](https://github.com/ValveSoftware/openvr/files/3610284/SteamVR-2019-09-13-PM_03_41_57.zip)

**Comment by peroht** [comment] 2019-10-10 20:28
I have traced this further and have a temporary solution for this. Please see this comment:

https://github.com/ValveSoftware/steamvr_unity_plugin/issues/536#issuecomment-540487404

**Comment by maxvollmer** [comment] 2019-10-12 10:30
I can confirm. I have this very same issue with my VR mod for Half-Life. I assume this happens because hl.exe is not registered as VR application in Steam.

**Comment by ajantaju** [comment] 2019-10-12 11:16
This explains a lot. Hope it gets resolved soon.

**Comment by maxvollmer** [comment] 2019-10-15 22:38
@JoeLudwig Shamelessly pinging you for attention.

**Comment by JoeLudwig** [comment] 2019-10-16 19:23
This will be fixed in 1.8.13

**Closed by JoeLudwig** 2019-10-16 19:23 UTC

**Comment by maxvollmer** [comment] 2019-10-17 20:55
Thanks for the quick response and fix! With today's SteamVR update my mod's beta testers report that saving controller bindings works again :)
