### ISSUE TITLE
IVRDriverInput for a single device driver not working.

### ISSUE THREAD

**Issue by Skaarah** [ValveSoftware/openvr#826] opened 2018-07-08 03:05 UTC
I have done everything I can think of and I still can't get my custom device driver to update any bindings. The profile and input component updates look fine. Below is a screen shot of the input debugger and I can't tell what I'm missing. The device values on the right are correct but the binding on the right shows nothing. I'm pretty certain it's something really small and easy but finding resources on IVRDriverInput implementations is slim. My server logs are all clean. The only thing that seems off is an attempt to grab "IVRControllerComponent_001" component but there is no more Controller component interface in the api. I've been trying to debug this for weeks. Please save me.

![screenshot_1](https://user-images.githubusercontent.com/7052075/42416318-4ef23610-8220-11e8-956d-d6d19020230d.png)

**Comment by Skaarah** [comment] 2018-07-08 03:12
This is what my activate looks like.
`EVRInitError OmniDevice::Activate(uint32_t unObjectId)
{
	deviceIndex = unObjectId;

	auto properties = vr::VRProperties();
	auto propContainer = vr::VRProperties()->TrackedDeviceToPropertyContainer(deviceIndex);
	properties->SetStringProperty(propContainer, ETrackedDeviceProperty::Prop_InputProfilePath_String, "{open_omni}/input/open_omni_controller_profile.json");
	properties->SetBoolProperty(propContainer, ETrackedDeviceProperty::Prop_NeverTracked_Bool, true);
	
	properties->SetStringProperty(propContainer, Prop_ModelNumber_String, "omni_controller");
	properties->SetStringProperty(propContainer, Prop_RegisteredDeviceType_String, "omni_controller");
	
	properties->SetInt32Property(propContainer, vr::Prop_ControllerRoleHint_Int32, TrackedControllerRole_OptOut);

	auto vrinput = vr::VRDriverInput();

	auto touchResult = vrinput->CreateBooleanComponent(propContainer, "/input/base/touch", &touchHandle);
	if(touchResult != EVRInputError::VRInputError_None)
	{
		OmniLog::AppendLine("Input base Touch failed code(%i)", touchResult);
		return EVRInitError::VRInitError_Driver_Unknown;
	}
	auto yResult = vrinput->CreateScalarComponent(propContainer, "/input/base/y", &yHandle, EVRScalarType::VRScalarType_Absolute, EVRScalarUnits::VRScalarUnits_NormalizedTwoSided);
	if(yResult != EVRInputError::VRInputError_None)
	{
		OmniLog::AppendLine("Input base Y failed code(%i)", yResult);
		return EVRInitError::VRInitError_Driver_Unknown;
	}
	auto xResult = vrinput->CreateScalarComponent(propContainer, "/input/base/x", &xHandle, EVRScalarType::VRScalarType_Absolute, EVRScalarUnits::VRScalarUnits_NormalizedTwoSided);
	if(xResult != EVRInputError::VRInputError_None)
	{
		OmniLog::AppendLine("Input base X failed code(%i)", xResult);
		return EVRInitError::VRInitError_Driver_Unknown;
	}

	pose.poseIsValid = false;

	return EVRInitError::VRInitError_None;
}`

And this is my profile
`{
  "jsonid" : "input_profile",
  "controller_type": "omni_controller",
  "legacy_binding" :  "{open_omni}/input/legacy_bindings_open_omni_controller.json",
  "input_bindingui_mode" : "single_device",
  "input_bindingui_right" :
  {
    "image": "{open_omni}/icons/open_omni_controller.svg"
  },
  "input_source" :
  {
    "/input/base" : { 
        "type" : "trackpad",
        "binding_image_point" : [ 115, 175 ]
    }
  }
}`

**Comment by spayne** [comment] 2018-07-08 15:46
I wrote an input driver last week, so maybe I can help.  

I wrote a "software" version of the knuckles EV2 device: https://github.com/spayne/soft_knuckles.   This sets up all of the inputs and the bindings are working.   You can use the debug interface to set the input states.  Skeletal animation is not done yet.  This might be a useful reference for you to play with and see if you can setup bindings against it.

If I look at the bottom left of your screenshot of the inputs debugger I see you have /actions/move/in/turnleft bound to .../base/touch and it is showing three rectangles and the value 0.0000 underneath it.  This is suspicious since .../base/touch is a boolean so I would expect more of a boolean representation (maybe a single square) on the left.  I'm away on vacation until the 16th so I can't go back in and check this.

A general comment I would like to add is that sometimes the bindings gui was not saving my bindings.  Sometimes this is my fault - ie I'd be setting my bindings in the 'keyboard' tab and not in the 'system' tab.  Other times *I think* it was because of a type mismatch between what was saved in my or default actions bindings and what was expected.  e.g. At one point in time I thought 'touch' should be a scalar - since xbox/and ps4 controllers are pressure sensitive - and in that situation I'd see logs complaining about /click being bound incorrrectly.   This is just a guess, but I it would be wise to ensure your bindings are being saved and restored as you expect and without warnings in your logs.  ie - set bindings, save them, go back to the config screen, go forwards to edit your config and make sure they are all there.

**Comment by Skaarah** [comment] 2018-07-13 04:19
So in a stab in the dark I decided to try and say it was a two handed device and then it starts working.
![screenshot_1](https://user-images.githubusercontent.com/7052075/42672198-4be12614-8619-11e8-8e42-3bfd603302e5.png)

**Comment by JoeLudwig** [comment] 2018-07-13 17:53
The "input_bindingui_mode" setting in your input profile controls how the UI binds that controller to actions. "hmd" will bind everything under /user/head, "controller_handed" will bind everything under /user/hand/right or /user/hand/left, and "single_device" will generally bind things under /devices/<something>. Gamepads and Vive trackers have special rules that cause them to be bound under custom paths (/user/gamepad for gamepads and various other things for trackers.)

If your controller is held in a hand, you want "controller_handed". Is that what you mean by "two handed device"?

**Comment by Skaarah** [comment] 2018-07-13 22:15
Thanks for the reply Joe. The controller is a treadmill so "single_device" makes more sense for it contextually. But when I list it as "controller_handed" in the profile it seems to work. Could there anything that prevents a "single_device" from being updating the binding properly even though the values on the right side are correct?

**Comment by JoeLudwig** [comment] 2018-07-14 01:57
Oh, *that* Omni.

Can you show me what the binding UI is showing for the config when you have it set to single_device, as well as post a copy of your binding file? (You can turn on input debugging and use the "export" button to get a file in a reasonable directory.)

**Comment by Skaarah** [comment] 2018-07-14 20:42
open_omni_controller_profile.json
```json
{
  "jsonid" : "input_profile",
  "controller_type": "omni_controller",
  "legacy_binding" :  "{open_omni}/input/legacy_bindings_open_omni_controller.json",
  "input_bindingui_mode" : "single_device",
  "input_bindingui_right" :
  {
    "image": "{open_omni}/icons/open_omni_controller.svg"
  },
  "input_source" :
  {
    "/input/trackpad" : { 
        "type" : "trackpad",
        "binding_image_point" : [ 115, 175 ]
    }
  }
}
```

exported_omni_controller_binding.json
```json
{
   "app_key" : "system.generated.tester.exe",
   "bindings" : {
      "/actions/legacy" : {
         "sources" : [
            {
               "inputs" : {
                  "position" : {
                     "output" : "/actions/legacy/in/left_axis0_value"
                  },
                  "touch" : {
                     "output" : "/actions/legacy/in/left_axis0_touch"
                  }
               },
               "mode" : "trackpad",
               "path" : "/devices/omni_controller/input/trackpad"
            }
         ]
      }
   },
   "controller_type" : "omni_controller",
   "description" : "",
   "name" : "Default bindings for legacy applications for Omni Controller"
}
```
![binding](https://user-images.githubusercontent.com/7052075/42728263-aa73b1d0-876b-11e8-98e2-4b483a1b5dc5.png)
![debugger](https://user-images.githubusercontent.com/7052075/42728264-acb12324-876b-11e8-9296-31430d4c6d11.png)

**Comment by Skaarah** [comment] 2018-07-15 19:36
Is there a tool for completely removing SteamVR and all of its settings and logs. I have a feeling I broke something along the way. Now when I quit it just hangs on "Preparing to quit"

**Comment by spayne** [comment] 2018-07-15 20:06
I would try and figure out what is going on since you are writing drivers.

Steamvr will hang on shutdown if a driver is hanging on deactivate.  I'd
use vrpathreg to see what drivers have been registered and remove any
drivers you don't need anymore (e.g.  maybe it's mine?).   Retest shutdown.

If it's your driver then look for blocking reads or writes that will
prevent thread.joins from succeeding.  Fix these.

**Comment by Skaarah** [comment] 2018-07-15 20:46
Currently, I have no threads. I will eventually but run frame works well enough while I'm trying to get the darn thing to work.

**Comment by cwlmyjm** [comment] 2018-08-13 04:06
Hi omni,
I think I am doing some thing as you. I am also developping driver for my custom device. But I got stock when bind device actions to application actions. I cannot bind device to actions, I have wrote binding files and checked in controller binding page, and sure that have no problem on binding. But in input debug page, it show  unbound on the left. 
I have also try to register my device as controller_handed, it work! 😢
This is the issue. #856 😄

**Comment by SamRelativeDimensions** [comment] 2018-09-13 23:49
Currently struggling with the same single_device binding issue here too. From the sounds of it, you all switched the "ui_mode" to "controller_handed" and it started working?

Can someone confirm that for me? I've tried that, but I end up with a blank binding screen that I then cannot back out of.
I can see my device outputting values (/input/joystick/x and /input/joystick/y), but when binding this in the binding menu, I can still only see the Oculus left touch thumbstick position (/user/hand/left/input/joystick/x) being bound to the action "Left Trackpad/Thumbstick Value". I can confirm that my binding is saving as I can exit SteamVR, load it back up, and look at the saved binding.

**Comment by SamRelativeDimensions** [comment] 2018-09-17 00:06
Hi all,

As a follow up to the other day, I've created my own issue #886 . 

I've attached my input profiles to it, but if any additional logs or screenshots are needed to help debug the issue just let me know. Alternatively, if you've found a solution, it would be greatly appreciated if it could be posted either on here, or my issue thread!

Thanks 👍

**Comment by JoeLudwig** [comment] 2018-11-27 18:07
This should be much improved with the new treadmill controller role: https://github.com/ValveSoftware/openvr/releases/tag/v1.1.3

Closing this in favor of #937 to track remaining treadmill issues.

**Closed by JoeLudwig** 2018-11-27 18:07 UTC
