### ISSUE TITLE
SteamVR menu breaks proximity sensor

### ISSUE THREAD

**Issue by muchcharles** [ValveSoftware/openvr#904] opened 2018-10-07 22:15 UTC
When the SteamVR menu is open, GetControllerState on the HMD to check the proximity sensor always fails.

			vr::VRControllerState_t HeadsetState;
			bool Result = VRSystem->GetControllerState(vr::k_unTrackedDeviceIndex_Hmd, &HeadsetState, sizeof(vr::VRControllerState_t))

Always results in Result == false.

This is on the latest SteamVR beta as of 10/7/2018.

I believe the root cause is probably the way the old input interface is being emulated via legacy bindings using the new one, and then app focus rules that shouldn't apply to the proximity sensor end up applying.

This means if the VR menu is open, users can't automatically toggle to 2D in my application when they take off the HMD.

**Comment by bddckr** [comment] 2018-10-08 13:45
Probably has nothing to do with the new input system at all since I have the same issue **since Sep 16, 2017**: #628

**Comment by kisak-valve** [comment] 2018-10-08 13:59
Closing as a duplicate of #628.

**Closed by kisak-valve** 2018-10-08 13:59 UTC
