### ISSUE TITLE
Software IPD setting for Oculus Rift S doesn't apply at SteamVR start

### ISSUE THREAD

**Issue by sergioberg** [ValveSoftware/openvr#1256] opened 2019-11-27 09:18 UTC
[c#] OpenVR.System.GetFloatTrackedDeviceProperty(OpenVR.k_unTrackedDeviceIndex_Hmd, ETrackedDeviceProperty.Prop_UserIpdMeters_Float, ref error)  returns default 63.0 (regardless of the value already set in Oculus app, before SteamVR starts) until the user changes software IPD setting in Oculus app.
This issue is observed in public and beta branches of SteamVR.

**Comment by LukeRoss00** [comment] 2019-11-27 10:39
Can confirm the same erroneous behavior from `IVRSystem::GetEyeToHeadTransform()` with the Oculus Rift CV1

**Comment by LaySoe** [comment] 2019-11-28 05:39
Duplicate of #

**Comment by JeffLeinbaugh** [comment] 2019-12-14 02:45
This is fixed in SteamVR 1.9.12
https://steamcommunity.com/games/250820/announcements/detail/3150762393109181780

**Closed by JeffLeinbaugh** 2019-12-14 02:45 UTC
